// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujhthimgwmbqzkuyjgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaHRoaW1nd21icXprdXlqZ3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTA0OTIsImV4cCI6MjA2ODE4NjQ5Mn0.O-ZRKd30IHVXMQEvBycaxLMUbHQBwgcwGPHxuJTe2-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});