// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctdkambpvfkkgsbdrssk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZGthbWJwdmZra2dzYmRyc3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDQ1NjQsImV4cCI6MjA2Nzk4MDU2NH0.5i32R7RhMvFFPgOVSSJOAMPiO1gDvLf5USVsgAiBFjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});